### ISSUE TITLE
Selecting a segment ?

### ISSUE THREAD

**Issue by carolinerosin** [Jungyubw/newTCAMT#104]
I imported an HL7 message by copying/pasting in the HL7 Encoded Message section.
Then I go to Test Data, but I don't see hoe to select a segment ?
![tcamt select segment](https://cloud.githubusercontent.com/assets/13591511/20077215/816a5460-a509-11e6-95e8-c49b9773a058.JPG)

**Comment by Jungyubw** [comment]
@carolinerosin Could you provide me your HL7 message txt?

Thanks
