### ISSUE TITLE
How do I validate ?

### ISSUE THREAD

**Issue by carolinerosin** [Jungyubw/newTCAMT#105]
I can't seem to find how to validate my Test Step message. I can clic on "CONTEXT FREE" or "CONTEXT BASED", but I don't get any report.

**Comment by Jungyubw** [comment]
Fixed,

When the tool is redeployed, Please update your profile (Import XML again) first.

Thanks.

**Comment by Jungyubw** [comment]
Please wait for Abedel to deploy the tool.
We will let you know

**Comment by carolinerosin** [comment]
I just tried again since TCAMT was redeployed.
I updated my profiles (importing all 3 xml files) again.

Now I get this error (I am trying context free) : 
![tcamt validation](https://cloud.githubusercontent.com/assets/13591511/20145992/1d8e1252-a670-11e6-97da-345daf63a580.JPG)

**Comment by Abdelghani90** [comment]
Hi caroline, I should check with hossam. this is an exception coming for the validator.

**Comment by carolinerosin** [comment]
The profile I upload (integration profile xml, constraints xml, value sets xml) currently works with the validation, so I think something must be transformed in TCAMT.
Also I checked my files and I don't have any element with a name or id "CQ_CQ"

**Comment by Jungyubw** [comment]
Fixed
