### ISSUE TITLE
Test Data Specification not in sync with message

### ISSUE THREAD

**Issue by carolinerosin** [Jungyubw/newTCAMT#110]
Looks like I am getting test data specification from another step.

Here is a view of the message (an ACK) - this is my second test step
![tcamt message](https://cloud.githubusercontent.com/assets/13591511/20116661/2ef874f6-a5cb-11e6-80ef-9de59d25e00a.JPG)

And here is the test data specification I see, which is the data from the first step, not the second
![tcamt tds](https://cloud.githubusercontent.com/assets/13591511/20116684/452bb6fc-a5cb-11e6-9446-2a761bc3ba3a.JPG)

**Comment by Jungyubw** [comment]
When did you get this error?

It looks that your screen shot is old version.

Could you refresh your browser and try it again?

Thanks,


On Nov 8, 2016, at 3:52 PM, Caroline Rosin <notifications@github.com<mailto:notifications@github.com>> wrote:

Looks like I am getting test data specification from another step.
Here is a view of the message (an ACK) - this is my second test step
[tcamt message]<https://cloud.githubusercontent.com/assets/13591511/20116661/2ef874f6-a5cb-11e6-80ef-9de59d25e00a.JPG>
And here is the test data specification I see, which is the data from the first step, not the second
[tcamt tds]<https://cloud.githubusercontent.com/assets/13591511/20116684/452bb6fc-a5cb-11e6-9446-2a761bc3ba3a.JPG>

**Comment by carolinerosin** [comment]
I refreshed - I still get the same issue.

**Comment by Jungyubw** [comment]
Fixed
