### ISSUE TITLE
Message content html (exported) is sometimes empty

### ISSUE THREAD

**Issue by carolinerosin** [Jungyubw/newTCAMT#112]
Message and screenshot of the html are attached (github doesn't let me attach an html). It does not happen with all my test steps and the message content in tcamt is correct
[Message.txt](https://github.com/Jungyubw/newTCAMT/files/579405/Message.txt)
![tcamt html](https://cloud.githubusercontent.com/assets/13591511/20117442/98f14a56-a5ce-11e6-9f65-b2402f5bb687.JPG)

**Comment by Jungyubw** [comment]
Fixed
