### ISSUE TITLE
IGAMT profile update

### ISSUE THREAD

**Issue by carolinerosin** [Jungyubw/newTCAMT#116]
When I change my profile in IGAMT, are the changes automatically loaded in TCAMT as well ?

**Comment by Jungyubw** [comment]
Yes. when you change the profile in IGAMT, it will be on loaded in TCAMT.
On Nov 16, 2016, at 9:47 AM, Caroline Rosin <notifications@github.com<mailto:notifications@github.com>> wrote:


When I change my profile in IGAMT, are the changes automatically loaded in TCAMT as well ?

**Comment by robnist** [comment]
I think we should rethink this.

I'd rather see a notification to the user in TCAMT stating something like, "There exist an update for Profile X in IGAMT, would you like to update? Previous Test cases may be affected"

What do you think?

**Comment by carolinerosin** [comment]
Yes I think a notification and update button are a good idea.
