### ISSUE TITLE
Test Step order not saved

### ISSUE THREAD

**Issue by larsonet9** [Jungyubw/newTCAMT#119]
I've reordered the test steps several times and saved them.  They appear to be properly ordered, but then later will revert to the wrong order.   As shown below.  The first test is ordered correctly, but the next three show the second step, followed by the first step.

![image](https://cloud.githubusercontent.com/assets/17886468/20760623/23e968b4-b6e6-11e6-9699-12fe0f41ea12.png)

**Comment by Jungyubw** [comment]
@Abdelghani90 Please Check tree position issue.
