### ISSUE TITLE
Test Case - Test Story - Description was lost

### ISSUE THREAD

**Issue by larsonet9** [Jungyubw/newTCAMT#120]
I don't have much detail on this one and not exactly sure when it happened, but I've lost all of the Descriptions in the Test Stories at the Test Case level.  These were in and saved, but then all at once I lost all of them (or at least noticed they disappeared all at once).  To be fair I was moving a lot things around and had test groups which were getting phased out to only have test cases and no groups, so it may have been part of that process.  I haven't noticed any other lost data, but Description is the only field I'm using at the Test Case Level.

**Comment by Jungyubw** [comment]
Sorry for inconvenience.
We will check what happen.

**Comment by Jungyubw** [comment]
@Abdelghani90 Please look at this issue.
