### ISSUE TITLE
Default value for test data categorization when NO test data is provided

### ISSUE THREAD

**Issue by RikiMerrick** [Jungyubw/newTCAMT#125]
Can we set "not test data categorization as the default value when no test data is provided for a test case?
Currently when you apply a template it applies the same test categorization codes as in the template - but not all test cases have the same elements populated, so then one has to go through and fix these by hand. Would be great to have that occur automatically.

**Comment by Jungyubw** [comment]
Need to discuss. I will answer it soon.

**Comment by Jungyubw** [comment]
We implemented Color highlighted warning for this.
