### ISSUE TITLE
Export Profile XML ZIP error

### ISSUE THREAD

**Issue by carolinerosin** [Jungyubw/newTCAMT#142]
I tried to export a profile from TCAMT and I got that error message:
{"text":"internalError","skip":false,"resourceId":null,"manualHandle":"false","scope":null,"date":null,"version":null,"id":null,"type":"danger"}

This is for an "imported XML profile", I haven't tried for an "IGAMT profile"

**Comment by Jungyubw** [comment]
I will check this today.

**Comment by Jungyubw** [comment]
Fixed. Next daily Deployment
