### ISSUE TITLE
Validation Result not showing up

### ISSUE THREAD

**Issue by carolinerosin** [Jungyubw/newTCAMT#144]
I try to validate my test data, I go to VALIDATION tab.
I select CONTEXT FREE. I can (quickly) see a message on the bottom saying "Performing Context-Free Validation". Then this message disappear, but there is no validation result showing up.

Same issue when I select "CONTEXT BASED".

The profile I use is an imported xml profile. I just tried to re-import it, but I am having the same issue

**Comment by Jungyubw** [comment]
This is same problem with Exporting.
I will fix it soon.

**Comment by Jungyubw** [comment]
Done.
