### ISSUE TITLE
ER Templates

### ISSUE THREAD

**Issue by smartinez290** [Jungyubw/newTCAMT#153]
A ER Template includes the test data categorizations?  I created one ER template and when I applied it, the test data included the categorization. 

Also, the OBX and PDA segments that are in the ER template are removed from the test data. They are in These segments are optional in the profile in question. They are no displayed even when I click "All usages"

**Comment by Jungyubw** [comment]
Er7 Template just has the Test Data.

Message Er7 Template contains full text of HL7 Message.
Segment Er7 Template is Line String of segment.

**Comment by Jungyubw** [comment]
@smartinez290 Could you show me this case tomorrow morning? I will stop by.

Thanks.
