### ISSUE TITLE
Test Story Configuration

### ISSUE THREAD

**Issue by smartinez290** [Jungyubw/newTCAMT#167]
This screen shot is not clear. I am not sure what "Empty content in Test Story" means. Does it apply to all the Test Stories?
![tsconfig](https://cloud.githubusercontent.com/assets/14842422/24963279/27b5e94c-1f6c-11e7-918d-80ddb72b6572.png)

**Comment by Jungyubw** [comment]
Yes it will be APPLY to all the Test Story when the resource bundle is generated.
