### ISSUE TITLE
Cloned a test group in LRI and it won't save

### ISSUE THREAD

**Issue by RikiMerrick** [Jungyubw/newTCAMT#170]
TCAMT currently not saving - cloned a test group and started making changes, but none were saved. Logged out and back in and it showed LRI hadn't been worked on since 4/11 - even though I just spent 30 min on it 4/17/4/18 EDT time -please check and fix.

**Comment by Jungyubw** [comment]
I will check this issue as soon as possible,

On Apr 18, 2017, at 12:34 AM, RikiMerrick <notifications@github.com<mailto:notifications@github.com>> wrote:


TCAMT currently not saving - cloned a test group and started making changes, but none were saved. Logged out and back in and it showed LRI hadn't been worked on since 4/11 - even though I just spent 30 min on it 4/17/4/18 EDT time -please check and fix.

**Comment by RikiMerrick** [comment]
thank you!

Riki

Riki Merrick
Vernetzt, LLC
rikimerrick@gmail.com
cell: 916.216.0052
skype: riki.merrick

**Comment by Jungyubw** [comment]
@RikiMerrick We tried to reproduce this issue, but it is working correctly. I would like to make sure you did "save" after you changed.

**Comment by RikiMerrick** [comment]
yes, I did hit save, which is why I got the note "error saving" eventually
- I think it might have had to do with the fact that I cloned ALL test
cases at the same time and it couldn't save them all. I am now cloning one
group at a time and it is saving, but even that takes quite a bit of time.

Workaround is a little more cumbersome, but working, so you can close this
ticket.

Riki

Riki Merrick
Vernetzt, LLC
rikimerrick@gmail.com
cell: 916.216.0052
skype: riki.merrick

**Comment by RikiMerrick** [comment]
I can not save a test group with 4 test cases, where 2 have 3 test steps each - so I broke it down into the test case - I coould save one, but not the second one, even after logging out and restarting my browser - it took more than 2 min to save the one it did save - any ideas?

**Comment by RikiMerrick** [comment]
I can not save a test group with 4 test cases, where 2 have 3 test steps each - so I broke it down into the test case - I could save one, but not the second one, even after logging out and restarting my browser - it took more than 2 min to save the one it did save - any ideas?
I am reluctant to work on this if I am not sure I can save the work...

**Comment by Jungyubw** [comment]
We have found an issue for unsaved TestPlan, I think it is related with your issue.

We will deploy it soon. I will let you know.

**Comment by RikiMerrick** [comment]
great - thank you!

Riki Merrick
Vernetzt, LLC
rikimerrick@gmail.com
cell: 916.216.0052
skype: riki.merrick

**Comment by Jungyubw** [comment]
Deployed. If you encounter same issue, let me know.

Thanks.
