### ISSUE TITLE
Special character formatting changes

### ISSUE THREAD

**Issue by RikiMerrick** [Jungyubw/newTCAMT#171]
Characters like the apostrophe or the quote show up like this EVERY TIME I open it back up, even after I think it has saved (NO "Unsaved Changes" label visible)

Example: 
LRI_1.2_1.1 - Post-Condition:
The test message information received by the EHR-S has been incorporated with the patient&apos;s record.

other changes are saving.

**Comment by Jungyubw** [comment]
Now I am investigating this issue.

**Comment by Jungyubw** [comment]
When I tried put the text:

_The test message information received by the EHR-S has been incorporated with the patient's record._

Then automatically changed by tool
--> _The test message information received by the EHR-S has been incorporated with the patient&apos;s record._

I understand it need to avoid HTML code conflicts, but not user friendly.
@Abdelghani90 any idea?

**Comment by Jungyubw** [comment]
@Abdelghani90 

I have tried to this at IGAMT. it is working well. Could you check how IGAMT froala editor to do this?

Thanks.

**Comment by RikiMerrick** [comment]
Oh - this is in TCAMT...
It does it for some, but not all...

Riki

Riki Merrick
Vernetzt, LLC
rikimerrick@gmail.com
cell: 916.216.0052
skype: riki.merrick

**Comment by RikiMerrick** [comment]
TCAMT still is having this issue - may be once imported into the tool publishing that won;t show up, so I will ignore this for now and NOT fix - here is a screenshot
![image](https://user-images.githubusercontent.com/22180804/27261173-374f0aea-53f2-11e7-9992-42572473e981.png)

**Comment by Abdelghani90** [comment]
@RikiMerrick.
Can you check if your test plan is still have this issue? I have tested it with the same data but i don't have this issue. 
Thanks 
Abdel

**Comment by RikiMerrick** [comment]
will do = I need to may be change the browser I use - I still am having
saving issues, which Eric does not have, so will do some testing later
today or tomorrow.

Riki

Riki Merrick
Vernetzt, LLC
rikimerrick@gmail.com
cell: 916.216.0052
skype: riki.merrick

**Comment by RikiMerrick** [comment]
yeah - working now, including the saving :)

Riki

Riki Merrick
Vernetzt, LLC
rikimerrick@gmail.com
cell: 916.216.0052
skype: riki.merrick
