### ISSUE TITLE
Tool seems stuck in loading test plans

### ISSUE THREAD

**Issue by RikiMerrick** [Jungyubw/newTCAMT#172]
When I logged on this AM I could not get to the testplans after 5 min.... see screenshot

![capture](https://cloud.githubusercontent.com/assets/22180804/25313898/6311ce6e-27ed-11e7-9672-0a1e581fbdd4.JPG)

**Comment by Jungyubw** [comment]
@RikiMerrick 

Currently TCAMT and IGAMT DB is not working. I am asking to Server administrator about this.
Sorry for this inconvenience.
