### ISSUE TITLE
tool or profile not listing all segments from the message instance

### ISSUE THREAD

**Issue by Healthedata1** [Jungyubw/newTCAMT#176]
For the test cases "Creatinine Clearance And "GHP" in the [Test Plan: LOI-EHR Test Plan](https://tcamt.nist.gov/tcamt/#/tp), the repeating ORC/OBR groups are not showing up in the Test Data.

for example in the test step "Test Step: LOI_7.0_2.1-GU_PRU":

![screen shot 2017-04-30 at 7 59 40 pm](https://cloud.githubusercontent.com/assets/7410922/25571020/bab2bfb4-2ddf-11e7-9d3a-5653cc681d0a.png)
![screen shot 2017-04-30 at 7 46 20 pm](https://cloud.githubusercontent.com/assets/7410922/25571022/bdb01d7e-2ddf-11e7-873f-eb2dcb2d881b.png)

I have cc'd Caroline as well in case the profiles the issue,

**Comment by Jungyubw** [comment]
@Healthedata1 I will check this.

**Comment by carolinerosin** [comment]
@Jungyubw I had a look at the XML representation, there is something wrong there. For some reason some segments are nested in the wrong group (OML_O21.PRIOR_RESULT), that is probably why they are not displayed in the Segment List

**Comment by Healthedata1** [comment]
Here is the raw message

MSH|^~\&#|NIST EHR^2.16.840.1.113883.3.72.5.22^ISO|NIST EHR
Facility^2.16.840.1.113883.3.72.5.23^ISO|NIST Test Lab
APP^2.16.840.1.113883.3.72.5.20^ISO|NIST Lab
Facility^2.16.840.1.113883.3.72.5.21^ISO|20130211184101-0500||OML^O21^OML_O21|NIST-LOI_7.0_1.1-GU_PRU|T|2.5.1|||AL|AL|||||LOI_GU_PRU_Profile^LOI
Base + PRU + GU^2.16.840.1.113883.9.85^ISO
PID|1||PATID70^^^NIST
MPI&2.16.840.1.113883.3.72.5.30.2&ISO^MR~000-00-0000^^^SSN&2.16.840.1.113883.4.1&ISO^SS||Nguyen^Thuy^Thi^III^^^L||19951010|F||2028-9^Asian^HL70005^^^^2.5.1^^Asian~2076-8^Native
Hawaiian or Other Pacific Islander^HL70005^^^^2.5.1^^Other Race|1447 North
Mar Vista^Apt 2^Pasadena^CA^91104^USA^H~25 West Mission Rd^Apt
2c^Alhambra^CA^91801^USA^H|||||||||||N^Not Hispanic or
Latino^HL70189^^^^2.5.1^^Not Hispanic or Latino||||||||N
NK1|1|Nguyen^Thuy^Thi^I^^^L|MTH^Mother^HL70063^^^^2.5.1^^Mother|1447 North
Mar Vista^Apt 2^Pasadena^CA^91104^USA^H~25 West Mission Rd^Apt
2c^Alhambra^CA^91801^USA^H|^^PH^^^626^5555555^1~^^X.400^Moms@email.com
~^^X.400^Dads@email.com~^^PH^^^626^4665599||N^Next-of-Kin^HL70131^^^^2.5.1^^Next
of Kin||||^^Laboratory Technician
NK1|2|Nguyen^Tran^Van^II^^^L|FTH^Father^HL70063^^^^2.5.1^^Father|25 West
Mission Rd^Apt 2c^Alhambra^CA^91801^USA^H~1447 North Mar Vista^Apt
2^Pasadena^CA^91104^USA^H|^^PH^^^626^5555556^2~^^X.400^Dads@email.com
~^^X.400^Moms@email.com~^^PH^^^626^3455555||N^Next-of-Kin^HL70131^^^^2.5.1^^Next
of Kin||||^^Laboratory Technician
ORC|NW|ORD70^NIST EHR^2.16.840.1.113883.3.72.5.24^ISO||GRP7^NIST
EHR^2.16.840.1.113883.3.72.5.24^ISO|||||201302191530|||2554560005^Yu^Ellen^^^^^^NPI&2.16.840.1.113883.4.6&ISO^L^^^NPI||^^PH^^^626^5555555
TQ1|1||||||20130220|20130319|F^Future Order^99USL^^^^^^Future Order
OBR|1|ORD70^NIST
EHR^2.16.840.1.113883.3.72.5.24^ISO||100^CMP^99USL^24323-8^Comprehensive
metabolic 2000 panel - Serum or
Plasma^LN^20130421^^CMP||||||||||||2554560005^Yu^Ellen^^^^^^NPI&2.16.840.1.113883.4.6&ISO^L^^^NPI|^^PH^^^626^5555555
DG1|1||E05.90^Hyperthyroidism (latent) (pre-adult)
(recurrent)^I10C|||W|||||||||1
DG1|2||R53.83^Other fatigue^I10C|||F|||||||||2
DG1|3||R63.4^abnormal weight loss^I10C|||F|||||||||3
ORC|NW|ORD71^NIST EHR^2.16.840.1.113883.3.72.5.24^ISO||GRP7^NIST
EHR^2.16.840.1.113883.3.72.5.24^ISO|||||201302191530|||2554560005^Yu^Ellen^^^^^^NPI&2.16.840.1.113883.4.6&ISO^L^^^NPI||^^PH^^^626^5555555
TQ1|1||||||20130220|20130319|F^Future Order^99USL^^^^^^Future Order
OBR|2|ORD71^NIST
EHR^2.16.840.1.113883.3.72.5.24^ISO||200^CBC_diff^99USL^57021-8^CBC W Auto
Differential panel in Blood^LN^20130421^^Complete Blood
Count||||||||||||2554560005^Yu^Ellen^^^^^^NPI&2.16.840.1.113883.4.6&ISO^L^^^NPI|^^PH^^^626^5555555
DG1|1||R53.83^Other fatigue^I10C|||F|||||||||1
ORC|NW|ORD72^NIST EHR^2.16.840.1.113883.3.72.5.24^ISO||GRP7^NIST
EHR^2.16.840.1.113883.3.72.5.24^ISO|||||201302191530|||2554560005^Yu^Ellen^^^^^^NPI&2.16.840.1.113883.4.6&ISO^L^^^NPI||^^PH^^^626^5555555
TQ1|1||||||20130220|20130319|F^Future Order^99USL^^^^^^Future Order
OBR|3|ORD72^NIST
EHR^2.16.840.1.113883.3.72.5.24^ISO||700^TSH^99USL^3016-3^Thyrotropin
[Units/volume] in Serum or Plasma^LN^20130421^^TSH -
Serum||||||||||||2554560005^Yu^Ellen^^^^^^NPI&2.16.840.1.113883.4.6&ISO^L^^^NPI|^^PH^^^626^5555555
DG1|1||E05.90^Hyperthyroidism (latent) (pre-adult)
(recurrent)^I10C|||W|||||||||1

Eric M Haas, DVM, MS
Health eData Inc
211 South Jefferson Street, Napa, CA, 94559
707.227.2608|Skype: haas.eric1
ehaas@healthedatainc.com <ehaas@healhtedatainc.com>

**Comment by carolinerosin** [comment]
@Jungyubw did you get a chance to look at this issue ?

**Comment by Jungyubw** [comment]
@carolinerosin I didn't have a chance to look at this and I am off today.
I will make it the first TODO tomorrow morning.

Thanks.

**Comment by carolinerosin** [comment]
No problem, let me know if you need help. Just FYI, I’ll be on vacation next week. I may work from home tomorrow and/or Friday because Nathan is sick (but I’ll have email access)

**Comment by Jungyubw** [comment]
@Healthedata1 
I have checked the your profile and message and I found the issue in my decomposing group logic. Today, I am working on IGAMT, so It will be fixed by end of this week.

Sorry for this inconvenience.

**Comment by Jungyubw** [comment]
@carolinerosin 
I hope Nathan will get well!
I will fix this issue by Friday. Thanks.
