### ISSUE TITLE
seem to have lost a few test stories again in deployment

### ISSUE THREAD

**Issue by RikiMerrick** [Jungyubw/newTCAMT#177]
the following test cases have no test stories (test objectives, comments, etc):
 1.LRI_4.0_1.1-NG
Final result to corrected (FRU)
 1.LRI_4.1_2.1-NG_FRU
 2.LRI_4.1_3.1-NG_FRU
 3.LRI_4.1_4.1-NG_FRU
 Final result to corrected (FRN)

Can you check if they got lost during deployment?

**Comment by Jungyubw** [comment]
Let me check this.


On May 4, 2017, at 12:52 AM, RikiMerrick <notifications@github.com<mailto:notifications@github.com>> wrote:


the following test cases have no test stories (test objectives, comments, etc):
1.LRI_4.0_1.1-NG
Final result to corrected (FRU)
1.LRI_4.1_2.1-NG_FRU
2.LRI_4.1_3.1-NG_FRU
3.LRI_4.1_4.1-NG_FRU
Final result to corrected (FRN)

Can you check if they got lost during deployment?
