### ISSUE TITLE
TestStory for a given TestStep is duplicated in html report

### ISSUE THREAD

**Issue by larsonet9** [Jungyubw/newTCAMT#93]
The TestStory.html that is generated when exporting the "ResourceBundle" duplicates all of the information.  The listing of all the sections show up twice.

![image](https://cloud.githubusercontent.com/assets/17886468/20018491/e4909566-a295-11e6-9f91-b661d41b5609.png)

**Comment by Jungyubw** [comment]
@larsonet9, We will fix it soon. Thanks.

**Comment by Jungyubw** [comment]
Fixed
